# -*- coding: utf-8 -*-
"""exdata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MLfibm0t68HieHWDgWyaQy-E06NqU-AN
"""


dfMentalhealth.head()

dfMentalhealth.info()

dfMentalhealth.describe()

for col in dfMentalhealth.columns:
  print(f"{col}:{dfMentalhealth[col].dtype}")

import seaborn as sns
df_iris = sns.load_dataset("iris")

print(df_iris.dtypes)

print("Moyenne :", df_iris["sepal_length"].mean())
print("Médiane :", df_iris["sepal_length"].median())
print("Mode :", df_iris["sepal_length"].mode()[0])

import matplotlib.pyplot as plt
import seaborn as sns

sns.histplot(df_iris["sepal_length"], bins=10, kde=True)
plt.show()